# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/Kayode/lab2/Nexys4DDR_Master.xdc

# Block Designs: bd/lab2_block/lab2_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block || ORIG_REF_NAME==lab2_block} -quiet] -quiet

# IP: bd/lab2_block/ip/lab2_block_half_adder_0_0/lab2_block_half_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_half_adder_0_0 || ORIG_REF_NAME==lab2_block_half_adder_0_0} -quiet] -quiet

# IP: bd/lab2_block/ip/lab2_block_full_adder_0_0/lab2_block_full_adder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_full_adder_0_0 || ORIG_REF_NAME==lab2_block_full_adder_0_0} -quiet] -quiet

# XDC: bd/lab2_block/lab2_block_ooc.xdc
